### ISSUE TITLE
what is the meaning of each tags?

### ISSUE THREAD

**Issue by mrmrn** [AminMozhgani/Persian_NER#2]
Dear Amin,
thank you very much for this repo.
I tested some example and I don't know the real meaning of some tags.
for example 
I found [this](https://emorynlp.github.io/nlp4j/components/named-entity-recognition.html) link for example for `fac` but I can not found the meaning of `قلب : I-fac`.
could you please guide me.

**Comment by AminMozhgani** [comment]
Hey, just take a look at source project documentations: https://github.com/HaniehP/PersianNER/blob/master/README.md
For example I-fac is facility.
