### ISSUE TITLE
NotFoundError: results/test/model.weights; No such file or directory

### ISSUE THREAD

**Issue by m-idasa** [AminMozhgani/Persian_NER#3]
hello Amin
I read your readme all but I have a problem running your code:

> 
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-5325291a722e>", line 1, in <module>
>     runfile('/home/user/Desktop/Persian_NER-master/evaluate.py', wdir='/home/user/Desktop/Persian_NER-master')
> 
>   File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/customize/spydercustomize.py", line 704, in runfile
>     execfile(filename, namespace)
> 
>   File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "/home/user/Desktop/Persian_NER-master/evaluate.py", line 64, in <module>
>     main()
> 
>   File "/home/user/Desktop/Persian_NER-master/evaluate.py", line 59, in main
>     model.restore_session(config.dir_model)
> 
>   File "/home/user/Desktop/Persian_NER-master/model/base_model.py", line 78, in restore_session
>     self.saver.restore(self.sess, dir_model)
> 
>   File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1536, in restore
>     if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
> 
>   File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 364, in checkpoint_exists
>     if file_io.get_matching_files(pathname):
> 
>   File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files
>     for single_filename in filename
> 
>   File "/home/user/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
>     c_api.TF_GetCode(self.status.status))
> 
> NotFoundError: results/test/model.weights; No such file or directory

please help me solve it.
Thank you

**Comment by m-idasa** [comment]
I found the problem, it was needed to run train.py before running evaluate.py.
but there was a big problem destroying accuracy alot!  in config there was needed to remove a line setting train and test dataset in line 78: filename_dev = filename_test = filename_train = "data/test.txt" # test
now I get a very good result about 97% accuracy

**Comment by AminMozhgani** [comment]
Totally correct, I just set all of them the same to enable running the code without training, after training you should change them.
